GET http://localhost:3000/hoge.html HTTP/1.1

###

GET http://localhost:3000/api/v1/test

###

# sign up
POST http://localhost:3000/api/v1/auth HTTP/1.1
content-type: application/json

{
  "name": "hippohack",
  "email":"example@example.com",
  "password":"password"
}

###

# sign up 2
POST http://localhost:3000/api/v1/auth HTTP/1.1
content-type: application/json

{
  "name": "benzoh",
  "email":"benzoh@example.com",
  "password":"password"
}

###

# sign in / correct
POST http://localhost:3000/api/v1/auth/sign_in
content-type: application/json

{
  "email":"example@example.com",
  "password":"password"
}

###

# sign in / mistaken
POST http://localhost:3000/api/v1/auth/sign_in
content-type: application/json

{
  "email":"example@example.com",
  "password":"hoge"
}

###

GET http://localhost:3000/api/v1/lotteries

###

GET http://localhost:3000/api/v1/lotteries/2

###

# トークンをくっつけるのは可能？？
POST http://localhost:3000/api/v1/lotteries
content-type: application/json

{
  "result": "はずれ",
  "memo": "この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。アカウント"
}

###

POST http://localhost:3000/api/v1/categories
content-type: application/json
access-token: 
client: 
uid: 

{
  "name":"category name",
  "slug":"category_name"
}

###

GET http://localhost:3000/api/v1/categories

###

GET http://localhost:3000/api/v1/categories/1